apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "z3rno.fullname" . }}
  labels:
    {{- include "z3rno.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.server.port | quote }}
  EMBEDDING_MODEL: "text-embedding-3-small"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "*"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
