apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "z3rno.server.fullname" . }}
  labels:
    {{- include "z3rno.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "z3rno.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "z3rno.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
        {{- include "z3rno.regionLabels" . | nindent 8 }}
    spec:
      {{- include "z3rno.topologySpread" . | nindent 6 }}
      {{- include "z3rno.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "z3rno.serviceAccountName" . }}
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "z3rno.fullname" . }}
            - secretRef:
                name: {{ include "z3rno.secretName" . }}
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
