{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "z3rno.worker.fullname" . }}
  labels:
    {{- include "z3rno.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "z3rno.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "z3rno.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "z3rno.serviceAccountName" . }}
      containers:
        - name: worker
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - {{ .Values.worker.command | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "z3rno.fullname" . }}
            - secretRef:
                name: {{ include "z3rno.secretName" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
