apiVersion: v1
kind: Service
metadata:
  name: {{ include "z3rno.server.fullname" . }}
  labels:
    {{- include "z3rno.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "z3rno.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
